Repository googleapis/gaxios, pull requests merged in 2020-09, with the labels that each got.

#334 build: fix nightly autosynth
  .kokoro/continuous/node12/lint.cfg
  .kokoro/continuous/node12/samples-test.cfg
  .kokoro/continuous/node12/system-test.cfg
  .kokoro/presubmit/node12/samples-test.cfg
  .kokoro/presubmit/node12/system-test.cfg
  .kokoro/release/publish.cfg
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  browser-test/browser-test-runner.ts
  synth.metadata
Labels: cla: yes

#335 build: update test config
  .github/workflows/ci.yaml
  .mocharc.js
  synth.metadata
Labels: cla: yes, context: none

#336 feat: add initial retry delay, and set default to 100ms
  README.md
  src/common.ts
  src/retry.ts
  test/test.retry.ts
Labels: cla: yes

#338 fix!: drop requirement on URL/combine url and params
  src/gaxios.ts
  test/test.getch.ts
Labels: cla: yes

#341 docs: add note about serialization options
  README.md
Labels: automerge, cla: yes
