Repository googleapis/gaxios, pull requests merged in 2020-07, with the labels that each got.

#304 chore: update CODEOWNERS
  .github/CODEOWNERS
Labels: automerge, cla: yes

#306 fix: typeo in nodejs .gitattribute
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full

#311 build: missing closing paren in publish script
  .kokoro/publish.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#310 chore: delete Node 8 presubmit tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: automerge, cla: yes

#315 chore: add config files for cloud-rad for node.js, delete Node 8 templates
  .kokoro/release/docs-devsite.cfg
  .kokoro/release/docs-devsite.sh
  api-extractor.json
  synth.metadata
Labels: automerge, cla: yes, context: partial

#314 build: add Node 8 tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: automerge, cla: yes, context: none

#316 chore: add dev dependencies for cloud-rad ref docs
  package.json
Labels: automerge, cla: yes

#317 build: rename _toc to toc
  .kokoro/release/docs-devsite.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#318 build: move gitattributes files to node templates
  .gitattributes
  synth.metadata
Labels: cla: yes, context: full

#321 chore(node): fix kokoro build path for cloud-rad
  .kokoro/release/docs-devsite.cfg
  synth.metadata
Labels: automerge, cla: yes, context: full

#319 feat: pass default adapter to adapter option
  README.md
  browser-test/test.browser.ts
  package.json
  src/common.ts
  src/gaxios.ts
  system-test/fixtures/sample/webpack.config.js
  test/test.getch.ts
  webpack-tests.config.js
  webpack.config.js
Labels: cla: yes
