Repository googleapis/gaxios, pull requests merged in 2022-04, with the labels that each got.

#475 fix: do not stringify form data
  package.json
  src/gaxios.ts
  test/test.getch.ts
Labels: size: s

#477 build!: drop node 10 from engines list, update typescript to 4.6.3
  .github/sync-repo-settings.yaml
  .github/workflows/ci.yaml
  .kokoro/continuous/node10/common.cfg
  .kokoro/continuous/node10/docs.cfg
  .kokoro/continuous/node10/lint.cfg
  .kokoro/continuous/node10/samples-test.cfg
  .kokoro/continuous/node10/system-test.cfg
  .kokoro/continuous/node10/test.cfg
  .kokoro/continuous/node8/common.cfg
  .kokoro/continuous/node8/test.cfg
  package.json
  src/gaxios.ts
  test/test.retry.ts
Labels: size: m

#483 feat: handling missing process global
  src/gaxios.ts
Labels: size: xs
