Repository googleapis/gaxios, pull requests merged in 2023-07, with the labels that each got.

#546 fix: translate GaxiosError message to object regardless of return type (return data as default)
  src/common.ts
  src/gaxios.ts
  test/test.getch.ts
Labels: size: m

#535 fix!: examine response content-type if no contentType is set
  README.md
  src/common.ts
  src/gaxios.ts
  test/test.getch.ts
Labels: next major: breaking change, size: m

#548 chore!: migrate to Node 14
  .github/sync-repo-settings.yaml
  .github/workflows/ci.yaml
  .kokoro/continuous/node12/browser-test.cfg
  .kokoro/continuous/node12/common.cfg
  .kokoro/continuous/node12/lint.cfg
  .kokoro/continuous/node12/samples-test.cfg
  .kokoro/continuous/node12/system-test.cfg
  .kokoro/continuous/node12/test.cfg
  .kokoro/presubmit/node10/common.cfg
  .kokoro/presubmit/node10/docs.cfg
  .kokoro/presubmit/node10/lint.cfg
  .kokoro/presubmit/node10/samples-test.cfg
  .kokoro/presubmit/node10/system-test.cfg
  .kokoro/presubmit/node10/test.cfg
  .kokoro/presubmit/node12/browser-test.cfg
  .kokoro/presubmit/node12/common.cfg
  .kokoro/presubmit/node12/samples-test.cfg
  .kokoro/presubmit/node12/system-test.cfg
  .kokoro/presubmit/node12/test.cfg
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
  package.json
Labels: size: m

#552 fix!: add status as a number to GaxiosError, change code to error code as a string
  src/common.ts
  test/test.getch.ts
Labels: size: s

#554 fix: add text to responseType switch statement
  src/common.ts
  src/gaxios.ts
Labels: size: xs

#556 fix: revert attempting to convert 'text/plain', leave as data in GaxiosError
  src/common.ts
Labels: size: xs

#558 fix: handle invalid json when Content-Type=application/json
  src/gaxios.ts
  test/test.getch.ts
Labels: size: s

#560 fix(deps): update https-proxy-agent to 7.0.1 and fix imports and tests
  package.json
  src/gaxios.ts
  test/test.getch.ts
Labels: size: xs
