Repository googleapis/gaxios, pull requests merged in 2024-04, with the labels that each got.

#609 feat: Enhance Error Redaction
  README.md
  package.json
  src/common.ts
  test/test.getch.ts
Labels: size: m

#610 feat: support multipart/related requests
  package.json
  src/common.ts
  src/gaxios.ts
  test/test.getch.ts
Labels: size: m

#613 fix: Error Redactor Case-Insensitive Matching
  src/common.ts
  test/test.getch.ts
Labels: size: s

#614 feat: Support `proxy` option
  README.md
  src/common.ts
  src/gaxios.ts
  test/test.getch.ts
Labels: size: l

#616 feat: Retry "408: Request Timeout" by Default
  README.md
  src/common.ts
  src/retry.ts
  test/test.retry.ts
Labels: size: xs
